host-group-name:
  hosts:
    host-1:
      ansible_host: 127.0.0.1
      ansible_user: ubuntu 
      ansible_connection: ssh 
      ansible_ssh_private_key_file: /path/private.pem
  vars:
    group_name: group_name # For SSH Banner
    env: staging
    users:
      user: sample-user-name
        key: "ssh-rsa 1234jkjasdkjaskfjaskfjsf...."
        state: present